name: 'Prueba de Outputs de la Action'

on: [workflow_dispatch]

jobs:
  probar-outputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # ESCENARIO 1: Rama con nombre CORRECTO (Ya funciona)
      - name: Ejecutar validador de ramas correcto
        id: validador_local
        uses: ./
        with:
          branch_name: 'feature/autenticacion-usuarios'
          allowed_prefixes: 'feature,bugfix,hotfix'

      # ESCENARIO 2: ROBUSTEZ - Entrada inválida / vacía (Requisito Parte 5)
      - name: Forzar error pasándole una rama vacía
        id: validador_error
        uses: ./
        with:
          branch_name: ''  # <--- Forzamos un valor vacío para probar la robustez
          allowed_prefixes: 'feature,bugfix'
        continue-on-error: true # Evita que rompa el workflow del todo para poder ver el log final
